name: PHP Lint (full)

on: pull_request

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint Code Base
      uses: github/super-linter@v3
      env:
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_PHP_BUILTIN: true
        VALIDATE_JSON: true
        VALIDATE_YAML: true
